server {
    listen 80;
    server_name www.merge.io.kr merge.io.kr;
    return 301 https://$host$request_uri; # 모든 접속을 HTTPS로 강제 전환
}

server {
    listen 443 ssl;
    server_name www.merge.io.kr merge.io.kr;

    ssl_certificate /etc/letsencrypt/live/merge.io.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/merge.io.kr/privkey.pem;

    client_max_body_size 20M;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 API (기존 설정 유지)
    location ~ ^/(api|users|oauth2|login/oauth2|uploads) {
        proxy_pass http://52.78.88.19:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 백엔드 어드민 API
    location /admin-api/ {
        rewrite ^/admin-api/(.*)$ /admin/$1 break;
        proxy_pass http://52.78.88.19:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}